<?php

use Illuminate\Database\Seeder;

class AdminPermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('admin_permissions')->delete();
        //PERMISSIONS
        DB::table('admin_permissions')->insert([
            ['id' => '1',
            'name' => '商品分類-讀',
            'slug' => 'ProductCategory-Reader',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '2',
            'name' => '商品分類-修',
            'slug' => 'ProductCategory-Editor',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '3',
            'name' => '商品分類-新',
            'slug' => 'ProductCategory-Creator',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '4',
            'name' => '商品分類-刪',
            'slug' => 'ProductCategory-Deleter',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '5',
            'name' => '商品-讀',
            'slug' => 'ProductIndex-Reader',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '6',
            'name' => '商品-修',
            'slug' => 'ProductIndex-Editor',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '7',
            'name' => '商品-新',
            'slug' => 'ProductIndex-Creator',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '8',
            'name' => '商品-刪',
            'slug' => 'ProductIndex-Deleter',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '9',
            'name' => '成本變更紀錄-讀',
            'slug' => 'ProductLog-Reader',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '10',
            'name' => '成本變更紀錄-修',
            'slug' => 'ProductLog-Editor',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '11',
            'name' => '成本變更紀錄-新',
            'slug' => 'ProductLog-Creator',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '12',
            'name' => '成本變更紀錄-刪',
            'slug' => 'ProductLog-Deleter',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '13',
            'name' => '進貨單-讀',
            'slug' => 'ProductReceipt-Reader',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '14',
            'name' => '進貨單-修',
            'slug' => 'ProductReceipt-Editor',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '15',
            'name' => '進貨單-新',
            'slug' => 'ProductReceipt-Creator',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '16',
            'name' => '進貨單-刪',
            'slug' => 'ProductReceipt-Deleter',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '17',
            'name' => '主題系列-讀',
            'slug' => 'ProductSeries-Reader',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '18',
            'name' => '主題系列-修',
            'slug' => 'ProductSeries-Editor',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '19',
            'name' => '主題系列-新',
            'slug' => 'ProductSeries-Creator',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '20',
            'name' => '主題系列-刪',
            'slug' => 'ProductSeries-Deleter',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '21',
            'name' => '廠商-讀',
            'slug' => 'ProductSupplier-Reader',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '22',
            'name' => '廠商-修',
            'slug' => 'ProductSupplier-Editor',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '23',
            'name' => '廠商-新',
            'slug' => 'ProductSupplier-Creator',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '24',
            'name' => '廠商-刪',
            'slug' => 'ProductSupplier-Deleter',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '25',
            'name' => '業務列表-讀',
            'slug' => 'Sales-Reader',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '26',
            'name' => '業務列表-修',
            'slug' => 'Sales-Editor',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '27',
            'name' => '業務列表-新',
            'slug' => 'Sales-Creator',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '28',
            'name' => '業務列表-刪',
            'slug' => 'Sales-Deleter',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '29',
            'name' => '配貨單-讀',
            'slug' => 'SalesAssign-Reader',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '30',
            'name' => '配貨單-修',
            'slug' => 'SalesAssign-Editor',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '31',
            'name' => '配貨單-新',
            'slug' => 'SalesAssign-Creator',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '32',
            'name' => '配貨單-刪',
            'slug' => 'SalesAssign-Deleter',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '33',
            'name' => '領貨單-讀',
            'slug' => 'SalesCollect-Reader',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '34',
            'name' => '領貨單-修',
            'slug' => 'SalesCollect-Editor',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '35',
            'name' => '領貨單-新',
            'slug' => 'SalesCollect-Creator',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '36',
            'name' => '領貨單-刪',
            'slug' => 'SalesCollect-Deleter',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '37',
            'name' => '業務公告-讀',
            'slug' => 'SalesNotes-Reader',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '38',
            'name' => '業務公告-修',
            'slug' => 'SalesNotes-Editor',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '39',
            'name' => '業務公告-新',
            'slug' => 'SalesNotes-Creator',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '40',
            'name' => '業務公告-刪',
            'slug' => 'SalesNotes-Deleter',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '41',
            'name' => '業務退貨-讀',
            'slug' => 'SalesRefund-Reader',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '42',
            'name' => '業務退貨-修',
            'slug' => 'SalesRefund-Editor',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '43',
            'name' => '業務退貨-新',
            'slug' => 'SalesRefund-Creator',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '44',
            'name' => '業務退貨-刪',
            'slug' => 'SalesRefund-Deleter',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '45',
            'name' => '庫存分類-讀',
            'slug' => 'StockCategory-Reader',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '46',
            'name' => '庫存分類-修',
            'slug' => 'StockCategory-Editor',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '47',
            'name' => '庫存分類-新',
            'slug' => 'StockCategory-Creator',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '48',
            'name' => '庫存分類-刪',
            'slug' => 'StockCategory-Deleter',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '49',
            'name' => '倉庫列表-讀',
            'slug' => 'Warehouse-Reader',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '50',
            'name' => '倉庫列表-修',
            'slug' => 'Warehouse-Editor',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '51',
            'name' => '倉庫列表-新',
            'slug' => 'Warehouse-Creator',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '52',
            'name' => '倉庫列表-刪',
            'slug' => 'Warehouse-Deleter',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '53',
            'name' => '地區-讀',
            'slug' => 'WebArea-Reader',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '54',
            'name' => '地區-修',
            'slug' => 'WebArea-Editor',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '55',
            'name' => '地區-新',
            'slug' => 'WebArea-Creator',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '56',
            'name' => '地區-刪',
            'slug' => 'WebArea-Deleter',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '57',
            'name' => '店鋪據點-讀',
            'slug' => 'WebLocation-Reader',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '58',
            'name' => '店鋪據點-修',
            'slug' => 'WebLocation-Editor',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '59',
            'name' => '店鋪據點-新',
            'slug' => 'WebLocation-Creator',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '60',
            'name' => '店鋪據點-刪',
            'slug' => 'WebLocation-Deleter',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '61',
            'name' => '庫存變更紀錄-讀',
            'slug' => 'StockLog-Reader',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '62',
            'name' => '庫存變更紀錄-修',
            'slug' => 'StockLog-Editor',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '63',
            'name' => '庫存變更紀錄-新',
            'slug' => 'StockLog-Creator',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '64',
            'name' => '庫存變更紀錄-刪',
            'slug' => 'StockLog-Deleter',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '65',
            'name' => '調撥單-讀',
            'slug' => 'Transfer-Reader',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '66',
            'name' => '調撥單-修',
            'slug' => 'Transfer-Editor',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '67',
            'name' => '調撥單-新',
            'slug' => 'Transfer-Creator',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
            ['id' => '68',
            'name' => '調撥單-刪',
            'slug' => 'Transfer-Deleter',
            'created_at' => date('Ymd'),
            'updated_at' => date('Ymd'),
            ],
        ]);
    }
}
