<?php

use Illuminate\Database\Seeder;

class WebAreaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //WAREHOUSE
        DB::table('web_area')->insert([
            ['id' => '1',
            'parent_id' => '0',
            'area_sort' => '1',
            'area_name' => '臺北市',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '2',
            'parent_id' => '1',
            'area_sort' => '1',
            'area_name' => '中正區',
            'zipcode' => '103',
            'type' => '2',
            ],
            ['id' => '3',
            'parent_id' => '1',
            'area_sort' => '1',
            'area_name' => '大同區',
            'zipcode' => '104',
            'type' => '2',
            ],
            ['id' => '4',
            'parent_id' => '1',
            'area_sort' => '1',
            'area_name' => '中山區',
            'zipcode' => '105',
            'type' => '2',
            ],
            ['id' => '5',
            'parent_id' => '1',
            'area_sort' => '1',
            'area_name' => '大安區',
            'zipcode' => '106',
            'type' => '2',
            ],
            ['id' => '6',
            'parent_id' => '1',
            'area_sort' => '1',
            'area_name' => '萬華區',
            'zipcode' => '108',
            'type' => '2',
            ],
            ['id' => '7',
            'parent_id' => '1',
            'area_sort' => '1',
            'area_name' => '信義區',
            'zipcode' => '110',
            'type' => '2',
            ],
            ['id' => '8',
            'parent_id' => '1',
            'area_sort' => '1',
            'area_name' => '士林區',
            'zipcode' => '111',
            'type' => '2',
            ],
            ['id' => '9',
            'parent_id' => '1',
            'area_sort' => '1',
            'area_name' => '北投區',
            'zipcode' => '112',
            'type' => '2',
            ],
            ['id' => '10',
            'parent_id' => '1',
            'area_sort' => '1',
            'area_name' => '內湖區',
            'zipcode' => '114',
            'type' => '2',
            ],
            ['id' => '11',
            'parent_id' => '1',
            'area_sort' => '1',
            'area_name' => '南港區',
            'zipcode' => '115',
            'type' => '2',
            ],
            ['id' => '12',
            'parent_id' => '1',
            'area_sort' => '1',
            'area_name' => '文山區',
            'zipcode' => '116',
            'type' => '2',
            ],
            ['id' => '13',
            'parent_id' => '0',
            'area_sort' => '2',
            'area_name' => '基隆市',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '14',
            'parent_id' => '13',
            'area_sort' => '2',
            'area_name' => '仁愛區',
            'zipcode' => '200',
            'type' => '2',
            ],
            ['id' => '15',
            'parent_id' => '13',
            'area_sort' => '2',
            'area_name' => '信義區',
            'zipcode' => '201',
            'type' => '2',
            ],
            ['id' => '16',
            'parent_id' => '13',
            'area_sort' => '2',
            'area_name' => '中正區',
            'zipcode' => '202',
            'type' => '2',
            ],
            ['id' => '17',
            'parent_id' => '13',
            'area_sort' => '2',
            'area_name' => '中山區',
            'zipcode' => '203',
            'type' => '2',
            ],
            ['id' => '18',
            'parent_id' => '13',
            'area_sort' => '2',
            'area_name' => '安樂區',
            'zipcode' => '204',
            'type' => '2',
            ],
            ['id' => '19',
            'parent_id' => '13',
            'area_sort' => '2',
            'area_name' => '暖暖區',
            'zipcode' => '205',
            'type' => '2',
            ],
            ['id' => '20',
            'parent_id' => '13',
            'area_sort' => '2',
            'area_name' => '七堵區',
            'zipcode' => '206',
            'type' => '2',
            ],
            ['id' => '21',
            'parent_id' => '0',
            'area_sort' => '3',
            'area_name' => '新北市',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '22',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '萬里區',
            'zipcode' => '207',
            'type' => '2',
            ],
            ['id' => '23',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '金山區',
            'zipcode' => '208',
            'type' => '2',
            ],
            ['id' => '24',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '板橋區',
            'zipcode' => '220',
            'type' => '2',
            ],
            ['id' => '25',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '汐止區',
            'zipcode' => '221',
            'type' => '2',
            ],
            ['id' => '26',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '深坑區',
            'zipcode' => '222',
            'type' => '2',
            ],
            ['id' => '27',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '石碇區',
            'zipcode' => '223',
            'type' => '2',
            ],
            ['id' => '28',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '瑞芳區',
            'zipcode' => '224',
            'type' => '2',
            ],
            ['id' => '29',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '平溪區',
            'zipcode' => '226',
            'type' => '2',
            ],
            ['id' => '30',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '雙溪區',
            'zipcode' => '227',
            'type' => '2',
            ],
            ['id' => '31',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '貢寮區',
            'zipcode' => '228',
            'type' => '2',
            ],
            ['id' => '32',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '新店區',
            'zipcode' => '231',
            'type' => '2',
            ],
            ['id' => '33',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '坪林區',
            'zipcode' => '232',
            'type' => '2',
            ],
            ['id' => '34',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '烏來區',
            'zipcode' => '233',
            'type' => '2',
            ],
            ['id' => '35',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '永和區',
            'zipcode' => '234',
            'type' => '2',
            ],
            ['id' => '36',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '中和區',
            'zipcode' => '235',
            'type' => '2',
            ],
            ['id' => '37',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '土城區',
            'zipcode' => '236',
            'type' => '2',
            ],
            ['id' => '38',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '三峽區',
            'zipcode' => '237',
            'type' => '2',
            ],
            ['id' => '39',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '樹林區',
            'zipcode' => '238',
            'type' => '2',
            ],
            ['id' => '40',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '鶯歌區',
            'zipcode' => '239',
            'type' => '2',
            ],
            ['id' => '41',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '三重區',
            'zipcode' => '241',
            'type' => '2',
            ],
            ['id' => '42',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '新莊區',
            'zipcode' => '242',
            'type' => '2',
            ],
            ['id' => '43',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '泰山區',
            'zipcode' => '243',
            'type' => '2',
            ],
            ['id' => '44',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '林口區',
            'zipcode' => '244',
            'type' => '2',
            ],
            ['id' => '45',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '蘆洲區',
            'zipcode' => '247',
            'type' => '2',
            ],
            ['id' => '46',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '五股區',
            'zipcode' => '248',
            'type' => '2',
            ],
            ['id' => '47',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '八里區',
            'zipcode' => '249',
            'type' => '2',
            ],
            ['id' => '48',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '淡水區',
            'zipcode' => '251',
            'type' => '2',
            ],
            ['id' => '49',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '三芝區',
            'zipcode' => '252',
            'type' => '2',
            ],
            ['id' => '50',
            'parent_id' => '21',
            'area_sort' => '3',
            'area_name' => '石門區',
            'zipcode' => '253',
            'type' => '2',
            ],
            ['id' => '51',
            'parent_id' => '0',
            'area_sort' => '4',
            'area_name' => '宜蘭縣',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '52',
            'parent_id' => '51',
            'area_sort' => '4',
            'area_name' => '宜蘭市',
            'zipcode' => '260',
            'type' => '2',
            ],
            ['id' => '53',
            'parent_id' => '51',
            'area_sort' => '4',
            'area_name' => '頭城鎮',
            'zipcode' => '261',
            'type' => '2',
            ],
            ['id' => '54',
            'parent_id' => '51',
            'area_sort' => '4',
            'area_name' => '礁溪鄉',
            'zipcode' => '262',
            'type' => '2',
            ],
            ['id' => '55',
            'parent_id' => '51',
            'area_sort' => '4',
            'area_name' => '壯圍鄉',
            'zipcode' => '263',
            'type' => '2',
            ],
            ['id' => '56',
            'parent_id' => '51',
            'area_sort' => '4',
            'area_name' => '員山鄉',
            'zipcode' => '264',
            'type' => '2',
            ],
            ['id' => '57',
            'parent_id' => '51',
            'area_sort' => '4',
            'area_name' => '羅東鎮',
            'zipcode' => '265',
            'type' => '2',
            ],
            ['id' => '58',
            'parent_id' => '51',
            'area_sort' => '4',
            'area_name' => '三星鄉',
            'zipcode' => '266',
            'type' => '2',
            ],
            ['id' => '59',
            'parent_id' => '51',
            'area_sort' => '4',
            'area_name' => '大同鄉',
            'zipcode' => '267',
            'type' => '2',
            ],
            ['id' => '60',
            'parent_id' => '51',
            'area_sort' => '4',
            'area_name' => '五結鄉',
            'zipcode' => '267',
            'type' => '2',
            ],
            ['id' => '61',
            'parent_id' => '51',
            'area_sort' => '4',
            'area_name' => '冬山鄉',
            'zipcode' => '269',
            'type' => '2',
            ],
            ['id' => '62',
            'parent_id' => '51',
            'area_sort' => '4',
            'area_name' => '蘇澳鎮',
            'zipcode' => '269',
            'type' => '2',
            ],
            ['id' => '63',
            'parent_id' => '51',
            'area_sort' => '4',
            'area_name' => '南澳鄉',
            'zipcode' => '272',
            'type' => '2',
            ],
            ['id' => '64',
            'parent_id' => '51',
            'area_sort' => '4',
            'area_name' => '釣魚臺列嶼',
            'zipcode' => '290',
            'type' => '2',
            ],
            ['id' => '65',
            'parent_id' => '0',
            'area_sort' => '5',
            'area_name' => '新竹市',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '66',
            'parent_id' => '65',
            'area_sort' => '5',
            'area_name' => '東區',
            'zipcode' => '300',
            'type' => '2',
            ],
            ['id' => '67',
            'parent_id' => '65',
            'area_sort' => '5',
            'area_name' => '北區',
            'zipcode' => '300',
            'type' => '2',
            ],
            ['id' => '68',
            'parent_id' => '65',
            'area_sort' => '5',
            'area_name' => '香山區 ',
            'zipcode' => '300',
            'type' => '2',
            ],
            ['id' => '69',
            'parent_id' => '0',
            'area_sort' => '6',
            'area_name' => '新竹縣',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '70',
            'parent_id' => '69',
            'area_sort' => '6',
            'area_name' => '竹北市',
            'zipcode' => '302',
            'type' => '2',
            ],
            ['id' => '71',
            'parent_id' => '69',
            'area_sort' => '6',
            'area_name' => '湖口鄉',
            'zipcode' => '303',
            'type' => '2',
            ],
            ['id' => '72',
            'parent_id' => '69',
            'area_sort' => '6',
            'area_name' => '新豐鄉',
            'zipcode' => '304',
            'type' => '2',
            ],
            ['id' => '73',
            'parent_id' => '69',
            'area_sort' => '6',
            'area_name' => '新埔鎮',
            'zipcode' => '305',
            'type' => '2',
            ],
            ['id' => '74',
            'parent_id' => '69',
            'area_sort' => '6',
            'area_name' => '關西鎮',
            'zipcode' => '306',
            'type' => '2',
            ],
            ['id' => '75',
            'parent_id' => '69',
            'area_sort' => '6',
            'area_name' => '芎林鄉',
            'zipcode' => '306',
            'type' => '2',
            ],
            ['id' => '76',
            'parent_id' => '69',
            'area_sort' => '6',
            'area_name' => '寶山鄉',
            'zipcode' => '308',
            'type' => '2',
            ],
            ['id' => '77',
            'parent_id' => '69',
            'area_sort' => '6',
            'area_name' => '竹東鎮',
            'zipcode' => '308',
            'type' => '2',
            ],
            ['id' => '78',
            'parent_id' => '69',
            'area_sort' => '6',
            'area_name' => '五峰鄉',
            'zipcode' => '311',
            'type' => '2',
            ],
            ['id' => '79',
            'parent_id' => '69',
            'area_sort' => '6',
            'area_name' => '橫山鄉',
            'zipcode' => '312',
            'type' => '2',
            ],
            ['id' => '80',
            'parent_id' => '69',
            'area_sort' => '6',
            'area_name' => '尖石鄉',
            'zipcode' => '313',
            'type' => '2',
            ],
            ['id' => '81',
            'parent_id' => '69',
            'area_sort' => '6',
            'area_name' => '北埔鄉',
            'zipcode' => '314',
            'type' => '2',
            ],
            ['id' => '82',
            'parent_id' => '69',
            'area_sort' => '6',
            'area_name' => '峨眉鄉',
            'zipcode' => '315',
            'type' => '2',
            ],
            ['id' => '83',
            'parent_id' => '0',
            'area_sort' => '7',
            'area_name' => '桃園縣',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '84',
            'parent_id' => '83',
            'area_sort' => '7',
            'area_name' => '中壢市',
            'zipcode' => '320',
            'type' => '2',
            ],
            ['id' => '85',
            'parent_id' => '83',
            'area_sort' => '7',
            'area_name' => '平鎮市',
            'zipcode' => '324',
            'type' => '2',
            ],
            ['id' => '86',
            'parent_id' => '83',
            'area_sort' => '7',
            'area_name' => '龍潭鄉',
            'zipcode' => '325',
            'type' => '2',
            ],
            ['id' => '87',
            'parent_id' => '83',
            'area_sort' => '7',
            'area_name' => '楊梅市',
            'zipcode' => '326',
            'type' => '2',
            ],
            ['id' => '88',
            'parent_id' => '83',
            'area_sort' => '7',
            'area_name' => '新屋鄉',
            'zipcode' => '327',
            'type' => '2',
            ],
            ['id' => '89',
            'parent_id' => '83',
            'area_sort' => '7',
            'area_name' => '觀音鄉',
            'zipcode' => '328',
            'type' => '2',
            ],
            ['id' => '90',
            'parent_id' => '83',
            'area_sort' => '7',
            'area_name' => '桃園市',
            'zipcode' => '330',
            'type' => '2',
            ],
            ['id' => '91',
            'parent_id' => '83',
            'area_sort' => '7',
            'area_name' => '龜山鄉',
            'zipcode' => '333',
            'type' => '2',
            ],
            ['id' => '92',
            'parent_id' => '83',
            'area_sort' => '7',
            'area_name' => '八德市',
            'zipcode' => '334',
            'type' => '2',
            ],
            ['id' => '93',
            'parent_id' => '83',
            'area_sort' => '7',
            'area_name' => '大溪鎮',
            'zipcode' => '335',
            'type' => '2',
            ],
            ['id' => '94',
            'parent_id' => '83',
            'area_sort' => '7',
            'area_name' => '復興鄉',
            'zipcode' => '336',
            'type' => '2',
            ],
            ['id' => '95',
            'parent_id' => '83',
            'area_sort' => '7',
            'area_name' => '大園鄉',
            'zipcode' => '337',
            'type' => '2',
            ],
            ['id' => '96',
            'parent_id' => '83',
            'area_sort' => '7',
            'area_name' => '蘆竹鄉',
            'zipcode' => '338',
            'type' => '2',
            ],
            ['id' => '97',
            'parent_id' => '0',
            'area_sort' => '8',
            'area_name' => '苗栗縣',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '98',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '竹南鎮',
            'zipcode' => '349',
            'type' => '2',
            ],
            ['id' => '99',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '頭份鎮',
            'zipcode' => '349',
            'type' => '2',
            ],
            ['id' => '100',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '三灣鄉',
            'zipcode' => '352',
            'type' => '2',
            ],
            ['id' => '101',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '南庄鄉',
            'zipcode' => '353',
            'type' => '2',
            ],
            ['id' => '102',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '獅潭鄉',
            'zipcode' => '354',
            'type' => '2',
            ],
            ['id' => '103',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '後龍鎮',
            'zipcode' => '356',
            'type' => '2',
            ],
            ['id' => '104',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '通霄鎮',
            'zipcode' => '357',
            'type' => '2',
            ],
            ['id' => '105',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '苑裡鎮',
            'zipcode' => '358',
            'type' => '2',
            ],
            ['id' => '106',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '苗栗市',
            'zipcode' => '360',
            'type' => '2',
            ],
            ['id' => '107',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '造橋鄉',
            'zipcode' => '361',
            'type' => '2',
            ],
            ['id' => '108',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '頭屋鄉',
            'zipcode' => '362',
            'type' => '2',
            ],
            ['id' => '109',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '公館鄉',
            'zipcode' => '363',
            'type' => '2',
            ],
            ['id' => '110',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '大湖鄉',
            'zipcode' => '364',
            'type' => '2',
            ],
            ['id' => '111',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '泰安鄉',
            'zipcode' => '365',
            'type' => '2',
            ],
            ['id' => '112',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '銅鑼鄉',
            'zipcode' => '366',
            'type' => '2',
            ],
            ['id' => '113',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '三義鄉',
            'zipcode' => '366',
            'type' => '2',
            ],
            ['id' => '114',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '西湖鄉',
            'zipcode' => '366',
            'type' => '2',
            ],
            ['id' => '115',
            'parent_id' => '97',
            'area_sort' => '8',
            'area_name' => '卓蘭鎮',
            'zipcode' => '369',
            'type' => '2',
            ],
            ['id' => '116',
            'parent_id' => '0',
            'area_sort' => '9',
            'area_name' => '臺中市',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '117',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '中區',
            'zipcode' => '400',
            'type' => '2',
            ],
            ['id' => '118',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '東區',
            'zipcode' => '401',
            'type' => '2',
            ],
            ['id' => '119',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '南區',
            'zipcode' => '402',
            'type' => '2',
            ],
            ['id' => '120',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '西區',
            'zipcode' => '403',
            'type' => '2',
            ],
            ['id' => '121',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '北區',
            'zipcode' => '404',
            'type' => '2',
            ],
            ['id' => '122',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '北屯區',
            'zipcode' => '406',
            'type' => '2',
            ],
            ['id' => '123',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '西屯區',
            'zipcode' => '407',
            'type' => '2',
            ],
            ['id' => '124',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '南屯區',
            'zipcode' => '408',
            'type' => '2',
            ],
            ['id' => '125',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '太平區',
            'zipcode' => '411',
            'type' => '2',
            ],
            ['id' => '126',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '大里區',
            'zipcode' => '412',
            'type' => '2',
            ],
            ['id' => '127',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '霧峰區',
            'zipcode' => '413',
            'type' => '2',
            ],
            ['id' => '128',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '烏日區',
            'zipcode' => '414',
            'type' => '2',
            ],
            ['id' => '129',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '豐原區',
            'zipcode' => '420',
            'type' => '2',
            ],
            ['id' => '130',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '后里區',
            'zipcode' => '421',
            'type' => '2',
            ],
            ['id' => '131',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '石岡區',
            'zipcode' => '422',
            'type' => '2',
            ],
            ['id' => '132',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '東勢區',
            'zipcode' => '423',
            'type' => '2',
            ],
            ['id' => '133',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '和平區',
            'zipcode' => '424',
            'type' => '2',
            ],
            ['id' => '134',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '新社區',
            'zipcode' => '426',
            'type' => '2',
            ],
            ['id' => '135',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '潭子區',
            'zipcode' => '427',
            'type' => '2',
            ],
            ['id' => '136',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '大雅區',
            'zipcode' => '428',
            'type' => '2',
            ],
            ['id' => '137',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '神岡區',
            'zipcode' => '429',
            'type' => '2',
            ],
            ['id' => '138',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '大肚區',
            'zipcode' => '432',
            'type' => '2',
            ],
            ['id' => '139',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '沙鹿區',
            'zipcode' => '433',
            'type' => '2',
            ],
            ['id' => '140',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '龍井區',
            'zipcode' => '434',
            'type' => '2',
            ],
            ['id' => '141',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '梧棲區',
            'zipcode' => '435',
            'type' => '2',
            ],
            ['id' => '142',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '清水區',
            'zipcode' => '436',
            'type' => '2',
            ],
            ['id' => '143',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '大甲區',
            'zipcode' => '437',
            'type' => '2',
            ],
            ['id' => '144',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '外埔區',
            'zipcode' => '438',
            'type' => '2',
            ],
            ['id' => '145',
            'parent_id' => '116',
            'area_sort' => '9',
            'area_name' => '大安區',
            'zipcode' => '439',
            'type' => '2',
            ],
            ['id' => '146',
            'parent_id' => '0',
            'area_sort' => '10',
            'area_name' => '彰化縣',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '147',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '彰化市',
            'zipcode' => '500',
            'type' => '2',
            ],
            ['id' => '148',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '芬園鄉',
            'zipcode' => '502',
            'type' => '2',
            ],
            ['id' => '149',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '花壇鄉',
            'zipcode' => '503',
            'type' => '2',
            ],
            ['id' => '150',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '秀水鄉',
            'zipcode' => '504',
            'type' => '2',
            ],
            ['id' => '151',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '鹿港鎮',
            'zipcode' => '505',
            'type' => '2',
            ],
            ['id' => '152',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '福興鄉',
            'zipcode' => '506',
            'type' => '2',
            ],
            ['id' => '153',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '線西鄉',
            'zipcode' => '507',
            'type' => '2',
            ],
            ['id' => '154',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '和美鎮',
            'zipcode' => '508',
            'type' => '2',
            ],
            ['id' => '155',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '伸港鄉',
            'zipcode' => '509',
            'type' => '2',
            ],
            ['id' => '156',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '員林鎮',
            'zipcode' => '510',
            'type' => '2',
            ],
            ['id' => '157',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '社頭鄉',
            'zipcode' => '511',
            'type' => '2',
            ],
            ['id' => '158',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '永靖鄉',
            'zipcode' => '512',
            'type' => '2',
            ],
            ['id' => '159',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '埔心鄉',
            'zipcode' => '513',
            'type' => '2',
            ],
            ['id' => '160',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '溪湖鎮',
            'zipcode' => '514',
            'type' => '2',
            ],
            ['id' => '161',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '大村鄉',
            'zipcode' => '515',
            'type' => '2',
            ],
            ['id' => '162',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '埔鹽鄉',
            'zipcode' => '516',
            'type' => '2',
            ],
            ['id' => '163',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '田中鎮',
            'zipcode' => '520',
            'type' => '2',
            ],
            ['id' => '164',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '北斗鎮',
            'zipcode' => '521',
            'type' => '2',
            ],
            ['id' => '165',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '田尾鄉',
            'zipcode' => '522',
            'type' => '2',
            ],
            ['id' => '166',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '埤頭鄉',
            'zipcode' => '523',
            'type' => '2',
            ],
            ['id' => '167',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '溪州鄉',
            'zipcode' => '524',
            'type' => '2',
            ],
            ['id' => '168',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '竹塘鄉',
            'zipcode' => '525',
            'type' => '2',
            ],
            ['id' => '169',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '二林鎮',
            'zipcode' => '526',
            'type' => '2',
            ],
            ['id' => '170',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '大城鄉',
            'zipcode' => '527',
            'type' => '2',
            ],
            ['id' => '171',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '芳苑鄉',
            'zipcode' => '528',
            'type' => '2',
            ],
            ['id' => '172',
            'parent_id' => '146',
            'area_sort' => '10',
            'area_name' => '二水鄉',
            'zipcode' => '530',
            'type' => '2',
            ],
            ['id' => '173',
            'parent_id' => '0',
            'area_sort' => '11',
            'area_name' => '南投縣',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '174',
            'parent_id' => '173',
            'area_sort' => '11',
            'area_name' => '南投市',
            'zipcode' => '540',
            'type' => '2',
            ],
            ['id' => '175',
            'parent_id' => '173',
            'area_sort' => '11',
            'area_name' => '中寮鄉',
            'zipcode' => '541',
            'type' => '2',
            ],
            ['id' => '176',
            'parent_id' => '173',
            'area_sort' => '11',
            'area_name' => '草屯鎮',
            'zipcode' => '542',
            'type' => '2',
            ],
            ['id' => '177',
            'parent_id' => '173',
            'area_sort' => '11',
            'area_name' => '國姓鄉',
            'zipcode' => '544',
            'type' => '2',
            ],
            ['id' => '178',
            'parent_id' => '173',
            'area_sort' => '11',
            'area_name' => '埔里鎮',
            'zipcode' => '545',
            'type' => '2',
            ],
            ['id' => '179',
            'parent_id' => '173',
            'area_sort' => '11',
            'area_name' => '仁愛鄉',
            'zipcode' => '546',
            'type' => '2',
            ],
            ['id' => '180',
            'parent_id' => '173',
            'area_sort' => '11',
            'area_name' => '名間鄉',
            'zipcode' => '551',
            'type' => '2',
            ],
            ['id' => '181',
            'parent_id' => '173',
            'area_sort' => '11',
            'area_name' => '集集鎮',
            'zipcode' => '552',
            'type' => '2',
            ],
            ['id' => '182',
            'parent_id' => '173',
            'area_sort' => '11',
            'area_name' => '水里鄉',
            'zipcode' => '553',
            'type' => '2',
            ],
            ['id' => '183',
            'parent_id' => '173',
            'area_sort' => '11',
            'area_name' => '魚池鄉',
            'zipcode' => '555',
            'type' => '2',
            ],
            ['id' => '184',
            'parent_id' => '173',
            'area_sort' => '11',
            'area_name' => '信義鄉',
            'zipcode' => '556',
            'type' => '2',
            ],
            ['id' => '185',
            'parent_id' => '173',
            'area_sort' => '11',
            'area_name' => '竹山鎮',
            'zipcode' => '557',
            'type' => '2',
            ],
            ['id' => '186',
            'parent_id' => '173',
            'area_sort' => '11',
            'area_name' => '鹿谷鄉',
            'zipcode' => '558',
            'type' => '2',
            ],
            ['id' => '187',
            'parent_id' => '0',
            'area_sort' => '12',
            'area_name' => '雲林縣',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '188',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '斗南鎮',
            'zipcode' => '630',
            'type' => '2',
            ],
            ['id' => '189',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '大埤鄉',
            'zipcode' => '631',
            'type' => '2',
            ],
            ['id' => '190',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '虎尾鎮',
            'zipcode' => '632',
            'type' => '2',
            ],
            ['id' => '191',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '土庫鎮',
            'zipcode' => '633',
            'type' => '2',
            ],
            ['id' => '192',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '褒忠鄉',
            'zipcode' => '634',
            'type' => '2',
            ],
            ['id' => '193',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '東勢鄉',
            'zipcode' => '635',
            'type' => '2',
            ],
            ['id' => '194',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '臺西鄉',
            'zipcode' => '636',
            'type' => '2',
            ],
            ['id' => '195',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '崙背鄉',
            'zipcode' => '637',
            'type' => '2',
            ],
            ['id' => '196',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '麥寮鄉',
            'zipcode' => '638',
            'type' => '2',
            ],
            ['id' => '197',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '斗六市',
            'zipcode' => '640',
            'type' => '2',
            ],
            ['id' => '198',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '林內鄉',
            'zipcode' => '643',
            'type' => '2',
            ],
            ['id' => '199',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '古坑鄉',
            'zipcode' => '646',
            'type' => '2',
            ],
            ['id' => '200',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '莿桐鄉',
            'zipcode' => '647',
            'type' => '2',
            ],
            ['id' => '201',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '西螺鎮',
            'zipcode' => '648',
            'type' => '2',
            ],
            ['id' => '202',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '二崙鄉',
            'zipcode' => '649',
            'type' => '2',
            ],
            ['id' => '203',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '北港鎮',
            'zipcode' => '651',
            'type' => '2',
            ],
            ['id' => '204',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '水林鄉',
            'zipcode' => '652',
            'type' => '2',
            ],
            ['id' => '205',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '口湖鄉',
            'zipcode' => '653',
            'type' => '2',
            ],
            ['id' => '206',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '四湖鄉',
            'zipcode' => '654',
            'type' => '2',
            ],
            ['id' => '207',
            'parent_id' => '187',
            'area_sort' => '12',
            'area_name' => '元長鄉',
            'zipcode' => '655',
            'type' => '2',
            ],
            ['id' => '208',
            'parent_id' => '0',
            'area_sort' => '13',
            'area_name' => '嘉義市',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '209',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '東區',
            'zipcode' => '600',
            'type' => '2',
            ],
            ['id' => '210',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '西區',
            'zipcode' => '600',
            'type' => '2',
            ],
            ['id' => '211',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '番路鄉',
            'zipcode' => '602',
            'type' => '2',
            ],
            ['id' => '212',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '梅山鄉',
            'zipcode' => '603',
            'type' => '2',
            ],
            ['id' => '213',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '竹崎鄉',
            'zipcode' => '604',
            'type' => '2',
            ],
            ['id' => '214',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '阿里山鄉',
            'zipcode' => '605',
            'type' => '2',
            ],
            ['id' => '215',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '中埔鄉',
            'zipcode' => '606',
            'type' => '2',
            ],
            ['id' => '216',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '大埔鄉',
            'zipcode' => '607',
            'type' => '2',
            ],
            ['id' => '217',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '水上鄉',
            'zipcode' => '608',
            'type' => '2',
            ],
            ['id' => '218',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '鹿草鄉',
            'zipcode' => '611',
            'type' => '2',
            ],
            ['id' => '219',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '太保市',
            'zipcode' => '612',
            'type' => '2',
            ],
            ['id' => '220',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '朴子市',
            'zipcode' => '613',
            'type' => '2',
            ],
            ['id' => '221',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '東石鄉',
            'zipcode' => '614',
            'type' => '2',
            ],
            ['id' => '222',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '六腳鄉',
            'zipcode' => '615',
            'type' => '2',
            ],
            ['id' => '223',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '新港鄉',
            'zipcode' => '616',
            'type' => '2',
            ],
            ['id' => '224',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '民雄鄉',
            'zipcode' => '621',
            'type' => '2',
            ],
            ['id' => '225',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '大林鎮',
            'zipcode' => '622',
            'type' => '2',
            ],
            ['id' => '226',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '溪口鄉',
            'zipcode' => '623',
            'type' => '2',
            ],
            ['id' => '227',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '義竹鄉',
            'zipcode' => '624',
            'type' => '2',
            ],
            ['id' => '228',
            'parent_id' => '208',
            'area_sort' => '13',
            'area_name' => '布袋鎮',
            'zipcode' => '625',
            'type' => '2',
            ],
            ['id' => '229',
            'parent_id' => '0',
            'area_sort' => '14',
            'area_name' => '臺南市',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '230',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '中西區',
            'zipcode' => '690',
            'type' => '2',
            ],
            ['id' => '231',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '東區',
            'zipcode' => '691',
            'type' => '2',
            ],
            ['id' => '232',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '南區',
            'zipcode' => '692',
            'type' => '2',
            ],
            ['id' => '233',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '北區',
            'zipcode' => '694',
            'type' => '2',
            ],
            ['id' => '234',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '安平區',
            'zipcode' => '697',
            'type' => '2',
            ],
            ['id' => '235',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '安南區',
            'zipcode' => '699',
            'type' => '2',
            ],
            ['id' => '236',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '永康區',
            'zipcode' => '710',
            'type' => '2',
            ],
            ['id' => '237',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '歸仁區',
            'zipcode' => '711',
            'type' => '2',
            ],
            ['id' => '238',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '新化區',
            'zipcode' => '712',
            'type' => '2',
            ],
            ['id' => '239',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '左鎮區',
            'zipcode' => '713',
            'type' => '2',
            ],
            ['id' => '240',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '玉井區',
            'zipcode' => '714',
            'type' => '2',
            ],
            ['id' => '241',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '楠西區',
            'zipcode' => '715',
            'type' => '2',
            ],
            ['id' => '242',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '南化區',
            'zipcode' => '716',
            'type' => '2',
            ],
            ['id' => '243',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '仁德區',
            'zipcode' => '717',
            'type' => '2',
            ],
            ['id' => '244',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '關廟區',
            'zipcode' => '718',
            'type' => '2',
            ],
            ['id' => '245',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '龍崎區',
            'zipcode' => '719',
            'type' => '2',
            ],
            ['id' => '246',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '官田區',
            'zipcode' => '720',
            'type' => '2',
            ],
            ['id' => '247',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '麻豆區',
            'zipcode' => '721',
            'type' => '2',
            ],
            ['id' => '248',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '佳里區',
            'zipcode' => '722',
            'type' => '2',
            ],
            ['id' => '249',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '西港區',
            'zipcode' => '723',
            'type' => '2',
            ],
            ['id' => '250',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '七股區',
            'zipcode' => '724',
            'type' => '2',
            ],
            ['id' => '251',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '將軍區',
            'zipcode' => '725',
            'type' => '2',
            ],
            ['id' => '252',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '學甲區',
            'zipcode' => '726',
            'type' => '2',
            ],
            ['id' => '253',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '北門區',
            'zipcode' => '727',
            'type' => '2',
            ],
            ['id' => '254',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '新營區',
            'zipcode' => '730',
            'type' => '2',
            ],
            ['id' => '255',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '後壁區',
            'zipcode' => '731',
            'type' => '2',
            ],
            ['id' => '256',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '白河區',
            'zipcode' => '732',
            'type' => '2',
            ],
            ['id' => '257',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '東山區',
            'zipcode' => '733',
            'type' => '2',
            ],
            ['id' => '258',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '六甲區',
            'zipcode' => '734',
            'type' => '2',
            ],
            ['id' => '259',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '下營區',
            'zipcode' => '735',
            'type' => '2',
            ],
            ['id' => '260',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '柳營區',
            'zipcode' => '736',
            'type' => '2',
            ],
            ['id' => '261',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '鹽水區',
            'zipcode' => '737',
            'type' => '2',
            ],
            ['id' => '262',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '善化區',
            'zipcode' => '741',
            'type' => '2',
            ],
            ['id' => '263',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '大內區',
            'zipcode' => '742',
            'type' => '2',
            ],
            ['id' => '264',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '山上區',
            'zipcode' => '743',
            'type' => '2',
            ],
            ['id' => '265',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '新市區',
            'zipcode' => '744',
            'type' => '2',
            ],
            ['id' => '266',
            'parent_id' => '229',
            'area_sort' => '14',
            'area_name' => '安定區',
            'zipcode' => '745',
            'type' => '2',
            ],
            ['id' => '267',
            'parent_id' => '0',
            'area_sort' => '15',
            'area_name' => '高雄市',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '268',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '新興區',
            'zipcode' => '800',
            'type' => '2',
            ],
            ['id' => '269',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '前金區',
            'zipcode' => '801',
            'type' => '2',
            ],
            ['id' => '270',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '苓雅區',
            'zipcode' => '802',
            'type' => '2',
            ],
            ['id' => '271',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '鼓山區',
            'zipcode' => '804',
            'type' => '2',
            ],
            ['id' => '272',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '旗津區',
            'zipcode' => '805',
            'type' => '2',
            ],
            ['id' => '273',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '前鎮區',
            'zipcode' => '806',
            'type' => '2',
            ],
            ['id' => '274',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '三民區',
            'zipcode' => '807',
            'type' => '2',
            ],
            ['id' => '275',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '楠梓區',
            'zipcode' => '811',
            'type' => '2',
            ],
            ['id' => '276',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '小港區',
            'zipcode' => '812',
            'type' => '2',
            ],
            ['id' => '277',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '左營區',
            'zipcode' => '813',
            'type' => '2',
            ],
            ['id' => '278',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '仁武區',
            'zipcode' => '814',
            'type' => '2',
            ],
            ['id' => '279',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '大社區',
            'zipcode' => '815',
            'type' => '2',
            ],
            ['id' => '280',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '岡山區',
            'zipcode' => '820',
            'type' => '2',
            ],
            ['id' => '281',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '路竹區',
            'zipcode' => '821',
            'type' => '2',
            ],
            ['id' => '282',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '阿蓮區',
            'zipcode' => '822',
            'type' => '2',
            ],
            ['id' => '283',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '田寮區',
            'zipcode' => '823',
            'type' => '2',
            ],
            ['id' => '284',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '燕巢區',
            'zipcode' => '824',
            'type' => '2',
            ],
            ['id' => '285',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '橋頭區',
            'zipcode' => '825',
            'type' => '2',
            ],
            ['id' => '286',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '梓官區',
            'zipcode' => '826',
            'type' => '2',
            ],
            ['id' => '287',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '彌陀區',
            'zipcode' => '827',
            'type' => '2',
            ],
            ['id' => '288',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '永安區',
            'zipcode' => '828',
            'type' => '2',
            ],
            ['id' => '289',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '湖內區',
            'zipcode' => '829',
            'type' => '2',
            ],
            ['id' => '290',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '鳳山區',
            'zipcode' => '830',
            'type' => '2',
            ],
            ['id' => '291',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '大寮區',
            'zipcode' => '831',
            'type' => '2',
            ],
            ['id' => '292',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '林園區',
            'zipcode' => '832',
            'type' => '2',
            ],
            ['id' => '293',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '鳥松區',
            'zipcode' => '833',
            'type' => '2',
            ],
            ['id' => '294',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '大樹區',
            'zipcode' => '830',
            'type' => '2',
            ],
            ['id' => '295',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '旗山區',
            'zipcode' => '832',
            'type' => '2',
            ],
            ['id' => '296',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '美濃區',
            'zipcode' => '833',
            'type' => '2',
            ],
            ['id' => '297',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '六龜區',
            'zipcode' => '834',
            'type' => '2',
            ],
            ['id' => '298',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '內門區',
            'zipcode' => '835',
            'type' => '2',
            ],
            ['id' => '299',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '杉林區',
            'zipcode' => '836',
            'type' => '2',
            ],
            ['id' => '300',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '甲仙區',
            'zipcode' => '837',
            'type' => '2',
            ],
            ['id' => '301',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '桃源區',
            'zipcode' => '838',
            'type' => '2',
            ],
            ['id' => '302',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '那瑪夏區',
            'zipcode' => '839',
            'type' => '2',
            ],
            ['id' => '303',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '茂林區',
            'zipcode' => '851',
            'type' => '2',
            ],
            ['id' => '304',
            'parent_id' => '267',
            'area_sort' => '15',
            'area_name' => '茄萣區',
            'zipcode' => '852',
            'type' => '2',
            ],
            ['id' => '305',
            'parent_id' => '0',
            'area_sort' => '16',
            'area_name' => '南海諸島',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '306',
            'parent_id' => '305',
            'area_sort' => '16',
            'area_name' => '東沙',
            'zipcode' => '817',
            'type' => '2',
            ],
            ['id' => '307',
            'parent_id' => '305',
            'area_sort' => '16',
            'area_name' => '南沙',
            'zipcode' => '819',
            'type' => '2',
            ],
            ['id' => '308',
            'parent_id' => '0',
            'area_sort' => '17',
            'area_name' => '澎湖縣',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '309',
            'parent_id' => '308',
            'area_sort' => '17',
            'area_name' => '馬公市',
            'zipcode' => '880',
            'type' => '2',
            ],
            ['id' => '310',
            'parent_id' => '308',
            'area_sort' => '17',
            'area_name' => '西嶼鄉',
            'zipcode' => '881',
            'type' => '2',
            ],
            ['id' => '311',
            'parent_id' => '308',
            'area_sort' => '17',
            'area_name' => '望安鄉',
            'zipcode' => '882',
            'type' => '2',
            ],
            ['id' => '312',
            'parent_id' => '308',
            'area_sort' => '17',
            'area_name' => '七美鄉',
            'zipcode' => '883',
            'type' => '2',
            ],
            ['id' => '313',
            'parent_id' => '308',
            'area_sort' => '17',
            'area_name' => '白沙鄉',
            'zipcode' => '883',
            'type' => '2',
            ],
            ['id' => '314',
            'parent_id' => '308',
            'area_sort' => '17',
            'area_name' => '湖西鄉',
            'zipcode' => '885',
            'type' => '2',
            ],
            ['id' => '315',
            'parent_id' => '0',
            'area_sort' => '18',
            'area_name' => '屏東縣',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '316',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '屏東市',
            'zipcode' => '900',
            'type' => '2',
            ],
            ['id' => '317',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '三地門鄉',
            'zipcode' => '901',
            'type' => '2',
            ],
            ['id' => '318',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '霧臺鄉',
            'zipcode' => '902',
            'type' => '2',
            ],
            ['id' => '319',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '瑪家鄉',
            'zipcode' => '903',
            'type' => '2',
            ],
            ['id' => '320',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '九如鄉',
            'zipcode' => '904',
            'type' => '2',
            ],
            ['id' => '321',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '里港鄉',
            'zipcode' => '905',
            'type' => '2',
            ],
            ['id' => '322',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '高樹鄉',
            'zipcode' => '906',
            'type' => '2',
            ],
            ['id' => '323',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '鹽埔鄉',
            'zipcode' => '907',
            'type' => '2',
            ],
            ['id' => '324',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '長治鄉',
            'zipcode' => '908',
            'type' => '2',
            ],
            ['id' => '325',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '麟洛鄉',
            'zipcode' => '909',
            'type' => '2',
            ],
            ['id' => '326',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '竹田鄉',
            'zipcode' => '911',
            'type' => '2',
            ],
            ['id' => '327',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '內埔鄉',
            'zipcode' => '912',
            'type' => '2',
            ],
            ['id' => '328',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '萬丹鄉',
            'zipcode' => '913',
            'type' => '2',
            ],
            ['id' => '329',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '潮州鎮',
            'zipcode' => '920',
            'type' => '2',
            ],
            ['id' => '330',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '泰武鄉',
            'zipcode' => '921',
            'type' => '2',
            ],
            ['id' => '331',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '來義鄉',
            'zipcode' => '922',
            'type' => '2',
            ],
            ['id' => '332',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '萬巒鄉',
            'zipcode' => '923',
            'type' => '2',
            ],
            ['id' => '333',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '崁頂鄉',
            'zipcode' => '924',
            'type' => '2',
            ],
            ['id' => '334',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '新埤鄉',
            'zipcode' => '925',
            'type' => '2',
            ],
            ['id' => '335',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '南州鄉',
            'zipcode' => '926',
            'type' => '2',
            ],
            ['id' => '336',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '林邊鄉',
            'zipcode' => '927',
            'type' => '2',
            ],
            ['id' => '337',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '東港鄉',
            'zipcode' => '928',
            'type' => '2',
            ],
            ['id' => '338',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '琉球鄉',
            'zipcode' => '929',
            'type' => '2',
            ],
            ['id' => '339',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '佳冬鄉',
            'zipcode' => '931',
            'type' => '2',
            ],
            ['id' => '340',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '新園鄉',
            'zipcode' => '932',
            'type' => '2',
            ],
            ['id' => '341',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '枋寮鄉',
            'zipcode' => '940',
            'type' => '2',
            ],
            ['id' => '342',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '枋山鄉',
            'zipcode' => '941',
            'type' => '2',
            ],
            ['id' => '343',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '春日鄉',
            'zipcode' => '942',
            'type' => '2',
            ],
            ['id' => '344',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '獅子鄉',
            'zipcode' => '943',
            'type' => '2',
            ],
            ['id' => '345',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '車城鄉',
            'zipcode' => '944',
            'type' => '2',
            ],
            ['id' => '346',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '牡丹鄉',
            'zipcode' => '945',
            'type' => '2',
            ],
            ['id' => '347',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '恆春鄉',
            'zipcode' => '946',
            'type' => '2',
            ],
            ['id' => '348',
            'parent_id' => '315',
            'area_sort' => '18',
            'area_name' => '滿州鄉',
            'zipcode' => '947',
            'type' => '2',
            ],
            ['id' => '349',
            'parent_id' => '0',
            'area_sort' => '19',
            'area_name' => '臺東縣',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '350',
            'parent_id' => '349',
            'area_sort' => '19',
            'area_name' => '臺東市',
            'zipcode' => '950',
            'type' => '2',
            ],
            ['id' => '351',
            'parent_id' => '349',
            'area_sort' => '19',
            'area_name' => '綠島鄉',
            'zipcode' => '951',
            'type' => '2',
            ],
            ['id' => '352',
            'parent_id' => '349',
            'area_sort' => '19',
            'area_name' => '蘭嶼鄉',
            'zipcode' => '952',
            'type' => '2',
            ],
            ['id' => '353',
            'parent_id' => '349',
            'area_sort' => '19',
            'area_name' => '延平鄉',
            'zipcode' => '953',
            'type' => '2',
            ],
            ['id' => '354',
            'parent_id' => '349',
            'area_sort' => '19',
            'area_name' => '卑南鄉',
            'zipcode' => '954',
            'type' => '2',
            ],
            ['id' => '355',
            'parent_id' => '349',
            'area_sort' => '19',
            'area_name' => '鹿野鄉',
            'zipcode' => '955',
            'type' => '2',
            ],
            ['id' => '356',
            'parent_id' => '349',
            'area_sort' => '19',
            'area_name' => '關山鎮',
            'zipcode' => '956',
            'type' => '2',
            ],
            ['id' => '357',
            'parent_id' => '349',
            'area_sort' => '19',
            'area_name' => '海端鄉',
            'zipcode' => '957',
            'type' => '2',
            ],
            ['id' => '358',
            'parent_id' => '349',
            'area_sort' => '19',
            'area_name' => '池上鄉',
            'zipcode' => '958',
            'type' => '2',
            ],
            ['id' => '359',
            'parent_id' => '349',
            'area_sort' => '19',
            'area_name' => '東河鄉',
            'zipcode' => '959',
            'type' => '2',
            ],
            ['id' => '360',
            'parent_id' => '349',
            'area_sort' => '19',
            'area_name' => '成功鎮',
            'zipcode' => '961',
            'type' => '2',
            ],
            ['id' => '361',
            'parent_id' => '349',
            'area_sort' => '19',
            'area_name' => '長濱鄉',
            'zipcode' => '962',
            'type' => '2',
            ],
            ['id' => '362',
            'parent_id' => '349',
            'area_sort' => '19',
            'area_name' => '太麻里鄉',
            'zipcode' => '963',
            'type' => '2',
            ],
            ['id' => '363',
            'parent_id' => '349',
            'area_sort' => '19',
            'area_name' => '金峰鄉',
            'zipcode' => '964',
            'type' => '2',
            ],
            ['id' => '364',
            'parent_id' => '349',
            'area_sort' => '19',
            'area_name' => '大武鄉',
            'zipcode' => '965',
            'type' => '2',
            ],
            ['id' => '365',
            'parent_id' => '349',
            'area_sort' => '19',
            'area_name' => '達仁鄉',
            'zipcode' => '966',
            'type' => '2',
            ],
            ['id' => '366',
            'parent_id' => '0',
            'area_sort' => '20',
            'area_name' => '花蓮縣',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '367',
            'parent_id' => '366',
            'area_sort' => '20',
            'area_name' => '花蓮市',
            'zipcode' => '969',
            'type' => '2',
            ],
            ['id' => '368',
            'parent_id' => '366',
            'area_sort' => '20',
            'area_name' => '新城鄉',
            'zipcode' => '971',
            'type' => '2',
            ],
            ['id' => '369',
            'parent_id' => '366',
            'area_sort' => '20',
            'area_name' => '秀林鄉',
            'zipcode' => '972',
            'type' => '2',
            ],
            ['id' => '370',
            'parent_id' => '366',
            'area_sort' => '20',
            'area_name' => '吉安鄉',
            'zipcode' => '973',
            'type' => '2',
            ],
            ['id' => '371',
            'parent_id' => '366',
            'area_sort' => '20',
            'area_name' => '壽豐鄉',
            'zipcode' => '974',
            'type' => '2',
            ],
            ['id' => '372',
            'parent_id' => '366',
            'area_sort' => '20',
            'area_name' => '鳳林鎮',
            'zipcode' => '975',
            'type' => '2',
            ],
            ['id' => '373',
            'parent_id' => '366',
            'area_sort' => '20',
            'area_name' => '光復鄉',
            'zipcode' => '976',
            'type' => '2',
            ],
            ['id' => '374',
            'parent_id' => '366',
            'area_sort' => '20',
            'area_name' => '豐濱鄉',
            'zipcode' => '977',
            'type' => '2',
            ],
            ['id' => '375',
            'parent_id' => '366',
            'area_sort' => '20',
            'area_name' => '瑞穗鄉',
            'zipcode' => '978',
            'type' => '2',
            ],
            ['id' => '376',
            'parent_id' => '366',
            'area_sort' => '20',
            'area_name' => '萬榮鄉',
            'zipcode' => '979',
            'type' => '2',
            ],
            ['id' => '377',
            'parent_id' => '366',
            'area_sort' => '20',
            'area_name' => '玉里鎮',
            'zipcode' => '971',
            'type' => '2',
            ],
            ['id' => '378',
            'parent_id' => '366',
            'area_sort' => '20',
            'area_name' => '卓溪鄉',
            'zipcode' => '972',
            'type' => '2',
            ],
            ['id' => '379',
            'parent_id' => '366',
            'area_sort' => '20',
            'area_name' => '富里鄉',
            'zipcode' => '973',
            'type' => '2',
            ],
            ['id' => '380',
            'parent_id' => '0',
            'area_sort' => '21',
            'area_name' => '金門縣',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '381',
            'parent_id' => '380',
            'area_sort' => '21',
            'area_name' => '金沙鎮',
            'zipcode' => '890',
            'type' => '2',
            ],
            ['id' => '382',
            'parent_id' => '380',
            'area_sort' => '21',
            'area_name' => '金湖鎮',
            'zipcode' => '891',
            'type' => '2',
            ],
            ['id' => '383',
            'parent_id' => '380',
            'area_sort' => '21',
            'area_name' => '金寧鄉',
            'zipcode' => '892',
            'type' => '2',
            ],
            ['id' => '384',
            'parent_id' => '380',
            'area_sort' => '21',
            'area_name' => '金城鎮',
            'zipcode' => '893',
            'type' => '2',
            ],
            ['id' => '385',
            'parent_id' => '380',
            'area_sort' => '21',
            'area_name' => '烈嶼鄉',
            'zipcode' => '894',
            'type' => '2',
            ],
            ['id' => '386',
            'parent_id' => '380',
            'area_sort' => '21',
            'area_name' => '烏坵鄉',
            'zipcode' => '896',
            'type' => '2',
            ],
            ['id' => '387',
            'parent_id' => '0',
            'area_sort' => '22',
            'area_name' => '連江縣',
            'zipcode' => '',
            'type' => '1',
            ],
            ['id' => '388',
            'parent_id' => '387',
            'area_sort' => '22',
            'area_name' => '南竿鄉',
            'zipcode' => '208',
            'type' => '2',
            ],
            ['id' => '389',
            'parent_id' => '387',
            'area_sort' => '22',
            'area_name' => '北竿鄉',
            'zipcode' => '210',
            'type' => '2',
            ],
            ['id' => '390',
            'parent_id' => '387',
            'area_sort' => '22',
            'area_name' => '莒光鄉',
            'zipcode' => '211',
            'type' => '2',
            ],
            ['id' => '391',
            'parent_id' => '387',
            'area_sort' => '22',
            'area_name' => '東引鄉',
            'zipcode' => '212',
            'type' => '2',
            ],
        ]);
    }
}
